name: Merge request

on:
  pull_request:
    branches: ['**']

jobs:
  merge_request:
    name: Merge request
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Install Dependencies
        run: npm ci
      - name: Run Tests
        run: npm test
