name: tag-release

on:
  push:
    tags:
      - v*

jobs:
  tagged-release:
    name: Tagged Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v3
      - name: Set up node 
        uses: actions/setup-node@v3
      - run: npm ci
      - name: Build
        run: npm run build
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          title: Production Build